apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currency-exchange-service
  labels:
    name: currency-exchange-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: currency-exchange-service
    spec:
      containers:
      - name: currency-exchange-service
        image: currency-exchange-service:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
  labels:
    name: currency-exchange-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: currency-exchange-service
